
modeh(1,complication(+person,-complication)).
modeb(1,experience(+person)).
modeb(1,age(+person)).
modeb(1,sexe(+person)).
modeb(1,hta(+person)).
modeb(1,diabete(+person)).
modeb(1,bpco(+person)).
modeb(1,asthme(+person)).
modeb(1,coronarien(+person)).
modeb(1,autres(+person)).
modeb(1,ic(+person)).
modeb(1,indication(+person)).
modeb(1,diagnostic(+person)).
modeb(1,patientobese(+person)).
modeb(1,higharcadepalete(+person)).
modeb(1,shortneck(+person)).
modeb(1,necktrauma(+person)).
modeb(1,beardormoustache(+person)).
modeb(1,largetongue(+person)).
modeb(1,openingmouth(+person)).
modeb(1,thyromentaldistance(+person)).
modeb(1,betweenhyoidboneandthyroid(+person)).
modeb(1,tumor(+person)).
modeb(1,epiglottitis(+person)).
modeb(1,recentnecksurgery(+person)).
modeb(1,hematoma(+person)).
modeb(1,cervicalcollar(+person)).
modeb(1,lemonscore(+person)).
modeb(1,elderly(+person)).
modeb(1,numerosonde(+person)).
modeb(1,niveaufixation(+person)).
modeb(1,cormack(+person)).
modeb(1,laryngodifficile(+person)).
modeb(1,nombretentatives(+person)).
modeb(1,autreoperateur(+person)).
modeb(1,dureeintubation(+person)).
modeb(1,eichman(+person)).
modeb(1,moyensupraglottique(+person)).
modeb(1,lequel(+person)).
modeb(1,intubationdifficile(+person)).

determination(complication/2, experience/1).
determination(complication/2, age/1).
determination(complication/2, sexe/1).
determination(complication/2, hta/1).
determination(complication/2, diabete/1).
determination(complication/2, bpco/1).
determination(complication/2, asthme/1).
determination(complication/2, coronarien/1).
determination(complication/2, autres/1).
determination(complication/2, ic/1).
determination(complication/2, indication/1).
determination(complication/2, diagnostic/1).
determination(complication/2, patientobese/1).
determination(complication/2, higharcadepalete/1).
determination(complication/2, shortneck/1).
determination(complication/2, necktrauma/1).
determination(complication/2, beardormoustache/1).
determination(complication/2, largetongue/1).
determination(complication/2, openingmouth/1).
determination(complication/2, thyromentaldistance/1).
determination(complication/2, betweenhyoidboneandthyroid/1).
determination(complication/2, tumor/1).
determination(complication/2, epiglottitis/1).
determination(complication/2, recentnecksurgery/1).
determination(complication/2, hematoma/1).
determination(complication/2, cervicalcollar/1).
determination(complication/2, lemonscore/1).
determination(complication/2, elderly/1).
determination(complication/2, numerosonde/1).
determination(complication/2, niveaufixation/1).
determination(complication/2, cormack/1).
determination(complication/2, laryngodifficile/1).
determination(complication/2, nombretentatives/1).
determination(complication/2, autreoperateur/1).
determination(complication/2, dureeintubation/1).
determination(complication/2, eichman/1).
determination(complication/2, moyensupraglottique/1).
determination(complication/2, lequel/1).
determination(complication/2, intubationdifficile/1).
determination(complication/2, barotraumatisme/1).
determination(complication/2, intubationoesophagienne/1).



set(verbose,1).

:- begin_bg.
person(patient1).
person(patient2).
person(patient3).
person(patient4).
person(patient5).
person(patient6).
person(patient7).
person(patient8).
person(patient9).
person(patient10).
person(patient11).
person(patient12).
person(patient13).
person(patient14).
person(patient15).
person(patient16).
person(patient17).
person(patient18).
person(patient19).
person(patient20).
person(patient21).
person(patient22).
person(patient23).
person(patient24).
person(patient25).
person(patient26).
person(patient27).
person(patient28).
person(patient29).
person(patient30).
person(patient31).
person(patient32).
person(patient33).
person(patient34).
person(patient35).
person(patient36).
person(patient37).
person(patient38).
person(patient39).
person(patient40).
person(patient41).
person(patient42).
person(patient43).
person(patient44).
person(patient45).
person(patient46).
person(patient47).
person(patient48).
person(patient49).
person(patient50).
person(patient51).
person(patient52).
person(patient53).
person(patient54).
person(patient55).
person(patient56).
person(patient57).
person(patient58).
person(patient59).
person(patient60).
person(patient61).
person(patient62).
person(patient63).
person(patient64).
person(patient65).
person(patient66).
person(patient67).
person(patient68).
person(patient69).
person(patient70).
person(patient71).
person(patient72).
person(patient73).
person(patient74).
person(patient75).
person(patient76).
person(patient77).
person(patient78).
person(patient79).
person(patient80).
person(patient81).
person(patient82).
person(patient83).
person(patient84).
person(patient85).
person(patient86).
person(patient87).
person(patient88).
person(patient89).
person(patient90).
person(patient91).
person(patient92).
person(patient93).
person(patient94).
person(patient95).
person(patient96).
person(patient97).
person(patient98).
person(patient99).
person(patient100).
person(patient101).
person(patient102).
person(patient103).
person(patient104).
person(patient105).
person(patient106).
person(patient107).
person(patient108).
person(patient109).
person(patient110).
person(patient111).
person(patient112).
person(patient113).
person(patient114).
person(patient115).
person(patient116).
person(patient117).
person(patient118).
experience(patient4).
experience(patient9).
experience(patient12).
experience(patient14).
experience(patient15).
experience(patient17).
experience(patient18).
experience(patient20).
experience(patient21).
experience(patient22).
experience(patient35).
experience(patient37).
experience(patient38).
experience(patient41).
experience(patient42).
experience(patient43).
experience(patient44).
experience(patient48).
experience(patient49).
experience(patient50).
experience(patient51).
experience(patient52).
experience(patient55).
experience(patient58).
experience(patient59).
experience(patient60).
experience(patient65).
experience(patient66).
experience(patient67).
experience(patient72).
experience(patient73).
experience(patient75).
experience(patient90).
experience(patient92).
experience(patient94).
experience(patient95).
experience(patient96).
experience(patient97).
experience(patient98).
experience(patient99).
experience(patient102).
experience(patient115).
experience(patient116).
experience(patient117).
experience(patient118).
sexe(patient3).
sexe(patient6).
sexe(patient10).
sexe(patient12).
sexe(patient15).
sexe(patient18).
sexe(patient19).
sexe(patient21).
sexe(patient23).
sexe(patient25).
sexe(patient29).
sexe(patient30).
sexe(patient34).
sexe(patient46).
sexe(patient54).
sexe(patient55).
sexe(patient56).
sexe(patient57).
sexe(patient58).
sexe(patient74).
sexe(patient75).
sexe(patient77).
sexe(patient82).
sexe(patient84).
sexe(patient86).
sexe(patient88).
sexe(patient91).
sexe(patient94).
sexe(patient96).
sexe(patient97).
sexe(patient99).
sexe(patient100).
sexe(patient101).
sexe(patient102).
sexe(patient105).
sexe(patient108).
sexe(patient110).
sexe(patient112).
sexe(patient113).
sexe(patient114).
sexe(patient115).
hta(patient1).
hta(patient3).
hta(patient5).
hta(patient6).
hta(patient7).
hta(patient9).
hta(patient14).
hta(patient15).
hta(patient21).
hta(patient25).
hta(patient26).
hta(patient30).
hta(patient31).
hta(patient32).
hta(patient33).
hta(patient36).
hta(patient38).
hta(patient40).
hta(patient42).
hta(patient54).
hta(patient55).
hta(patient56).
hta(patient60).
hta(patient65).
hta(patient66).
hta(patient77).
hta(patient80).
hta(patient83).
hta(patient84).
hta(patient87).
hta(patient88).
hta(patient90).
hta(patient92).
hta(patient93).
hta(patient97).
hta(patient99).
hta(patient100).
hta(patient104).
hta(patient107).
hta(patient112).
hta(patient114).
hta(patient115).
hta(patient117).
hta(patient118).
diabete(patient3).
diabete(patient5).
diabete(patient9).
diabete(patient19).
diabete(patient21).
diabete(patient23).
diabete(patient25).
diabete(patient26).
diabete(patient28).
diabete(patient30).
diabete(patient33).
diabete(patient42).
diabete(patient51).
diabete(patient55).
diabete(patient65).
diabete(patient66).
diabete(patient74).
diabete(patient77).
diabete(patient82).
diabete(patient84).
diabete(patient87).
diabete(patient88).
diabete(patient90).
diabete(patient97).
diabete(patient100).
diabete(patient103).
diabete(patient104).
diabete(patient109).
diabete(patient112).
diabete(patient114).
diabete(patient115).
diabete(patient117).
diabete(patient118).
bpco(patient6).
bpco(patient8).
bpco(patient12).
bpco(patient15).
bpco(patient22).
bpco(patient60).
bpco(patient76).
bpco(patient81).
bpco(patient95).
bpco(patient109).
bpco(patient111).
asthme(patient72).
asthme(patient94).
asthme(patient116).
coronarien(patient1).
coronarien(patient9).
coronarien(patient12).
coronarien(patient28).
coronarien(patient33).
coronarien(patient37).
coronarien(patient45).
coronarien(patient65).
coronarien(patient70).
coronarien(patient78).
coronarien(patient87).
coronarien(patient88).
coronarien(patient90).
coronarien(patient104).
coronarien(patient114).
ic(patient1).
ic(patient22).
ic(patient36).
ic(patient37).
ic(patient80).
ic(patient87).
ic(patient88).
ic(patient99).
ic(patient111).
ic(patient117).
indication(patient1).
indication(patient17).
indication(patient51).
indication(patient84).
indication(patient87).
indication(patient88).
indication(patient101).
indication(patient115).
indication(patient116).
patientobese(patient3).
patientobese(patient5).
patientobese(patient6).
patientobese(patient10).
patientobese(patient12).
patientobese(patient14).
patientobese(patient15).
patientobese(patient17).
patientobese(patient21).
patientobese(patient25).
patientobese(patient26).
patientobese(patient33).
patientobese(patient34).
patientobese(patient36).
patientobese(patient54).
patientobese(patient56).
patientobese(patient64).
patientobese(patient65).
patientobese(patient74).
patientobese(patient78).
patientobese(patient79).
patientobese(patient80).
patientobese(patient84).
patientobese(patient91).
patientobese(patient97).
patientobese(patient102).
patientobese(patient104).
patientobese(patient107).
patientobese(patient108).
patientobese(patient112).
patientobese(patient115).
patientobese(patient118).
higharcadepalete(patient4).
higharcadepalete(patient9).
higharcadepalete(patient12).
higharcadepalete(patient16).
higharcadepalete(patient22).
higharcadepalete(patient37).
higharcadepalete(patient40).
higharcadepalete(patient43).
higharcadepalete(patient49).
higharcadepalete(patient66).
higharcadepalete(patient78).
higharcadepalete(patient83).
higharcadepalete(patient88).
shortneck(patient3).
shortneck(patient6).
shortneck(patient10).
shortneck(patient15).
shortneck(patient17).
shortneck(patient21).
shortneck(patient25).
shortneck(patient33).
shortneck(patient34).
shortneck(patient36).
shortneck(patient42).
shortneck(patient48).
shortneck(patient49).
shortneck(patient54).
shortneck(patient56).
shortneck(patient60).
shortneck(patient69).
shortneck(patient74).
shortneck(patient78).
shortneck(patient80).
shortneck(patient87).
shortneck(patient91).
shortneck(patient96).
shortneck(patient97).
shortneck(patient99).
shortneck(patient102).
shortneck(patient104).
shortneck(patient115).
necktrauma(patient48).
necktrauma(patient107).
beardormoustache(patient1).
beardormoustache(patient7).
beardormoustache(patient8).
beardormoustache(patient12).
beardormoustache(patient14).
beardormoustache(patient23).
beardormoustache(patient27).
beardormoustache(patient42).
beardormoustache(patient53).
beardormoustache(patient65).
beardormoustache(patient106).
beardormoustache(patient109).
largetongue(patient2).
largetongue(patient4).
largetongue(patient5).
largetongue(patient6).
largetongue(patient7).
largetongue(patient8).
largetongue(patient9).
largetongue(patient11).
largetongue(patient12).
largetongue(patient15).
largetongue(patient16).
largetongue(patient23).
largetongue(patient26).
largetongue(patient27).
largetongue(patient32).
largetongue(patient36).
largetongue(patient37).
largetongue(patient52).
largetongue(patient53).
largetongue(patient64).
largetongue(patient65).
largetongue(patient66).
largetongue(patient69).
openingmouth(patient3).
openingmouth(patient4).
openingmouth(patient6).
openingmouth(patient7).
openingmouth(patient11).
openingmouth(patient17).
openingmouth(patient21).
openingmouth(patient29).
openingmouth(patient40).
openingmouth(patient42).
openingmouth(patient49).
openingmouth(patient66).
openingmouth(patient75).
openingmouth(patient78).
openingmouth(patient83).
openingmouth(patient95).
openingmouth(patient99).
openingmouth(patient109).
openingmouth(patient112).
openingmouth(patient115).
thyromentaldistance(patient6).
thyromentaldistance(patient7).
thyromentaldistance(patient49).
thyromentaldistance(patient54).
thyromentaldistance(patient55).
thyromentaldistance(patient57).
thyromentaldistance(patient69).
thyromentaldistance(patient71).
thyromentaldistance(patient94).
thyromentaldistance(patient97).
thyromentaldistance(patient98).
thyromentaldistance(patient102).
thyromentaldistance(patient104).
thyromentaldistance(patient118).
betweenhyoidboneandthyroid(patient7).
betweenhyoidboneandthyroid(patient23).
betweenhyoidboneandthyroid(patient54).
betweenhyoidboneandthyroid(patient69).
betweenhyoidboneandthyroid(patient96).
betweenhyoidboneandthyroid(patient104).
recentnecksurgery(patient6).
cervicalcollar(patient48).
lemonscore(patient13).
lemonscore(patient18).
lemonscore(patient19).
lemonscore(patient20).
lemonscore(patient24).
lemonscore(patient28).
lemonscore(patient30).
lemonscore(patient31).
lemonscore(patient35).
lemonscore(patient38).
lemonscore(patient39).
lemonscore(patient41).
lemonscore(patient44).
lemonscore(patient45).
lemonscore(patient46).
lemonscore(patient47).
lemonscore(patient50).
lemonscore(patient51).
lemonscore(patient52).
lemonscore(patient58).
lemonscore(patient59).
lemonscore(patient61).
lemonscore(patient62).
lemonscore(patient63).
lemonscore(patient67).
lemonscore(patient68).
lemonscore(patient70).
lemonscore(patient72).
lemonscore(patient73).
lemonscore(patient76).
lemonscore(patient77).
lemonscore(patient79).
lemonscore(patient82).
lemonscore(patient84).
lemonscore(patient85).
lemonscore(patient86).
lemonscore(patient88).
lemonscore(patient89).
lemonscore(patient90).
lemonscore(patient92).
lemonscore(patient93).
lemonscore(patient100).
lemonscore(patient101).
lemonscore(patient103).
lemonscore(patient105).
lemonscore(patient108).
lemonscore(patient110).
lemonscore(patient111).
lemonscore(patient113).
lemonscore(patient114).
lemonscore(patient116).
lemonscore(patient117).
elderly(patient1).
elderly(patient3).
elderly(patient4).
elderly(patient7).
elderly(patient9).
elderly(patient14).
elderly(patient21).
elderly(patient22).
elderly(patient23).
elderly(patient25).
elderly(patient28).
elderly(patient42).
elderly(patient45).
elderly(patient51).
elderly(patient55).
elderly(patient60).
elderly(patient65).
elderly(patient70).
elderly(patient77).
elderly(patient88).
elderly(patient109).
elderly(patient112).
numerosonde(patient16).
numerosonde(patient48).
numerosonde(patient52).
numerosonde(patient56).
numerosonde(patient58).
niveaufixation(patient16).
niveaufixation(patient48).
niveaufixation(patient52).
niveaufixation(patient54).
niveaufixation(patient56).
niveaufixation(patient58).
niveaufixation(patient66).
niveaufixation(patient84).
niveaufixation(patient88).
niveaufixation(patient101).
niveaufixation(patient106).
laryngodifficile(patient1).
laryngodifficile(patient2).
laryngodifficile(patient3).
laryngodifficile(patient4).
laryngodifficile(patient5).
laryngodifficile(patient8).
laryngodifficile(patient9).
laryngodifficile(patient12).
laryngodifficile(patient14).
laryngodifficile(patient15).
laryngodifficile(patient16).
laryngodifficile(patient20).
laryngodifficile(patient33).
laryngodifficile(patient37).
laryngodifficile(patient49).
laryngodifficile(patient53).
laryngodifficile(patient58).
laryngodifficile(patient59).
laryngodifficile(patient69).
laryngodifficile(patient71).
laryngodifficile(patient73).
laryngodifficile(patient79).
laryngodifficile(patient81).
laryngodifficile(patient83).
laryngodifficile(patient96).
laryngodifficile(patient97).
laryngodifficile(patient99).
laryngodifficile(patient102).
laryngodifficile(patient103).
laryngodifficile(patient104).
laryngodifficile(patient112).
laryngodifficile(patient117).
laryngodifficile(patient118).
autreoperateur(patient4).
autreoperateur(patient5).
autreoperateur(patient6).
autreoperateur(patient8).
autreoperateur(patient16).
autreoperateur(patient26).
autreoperateur(patient31).
autreoperateur(patient37).
autreoperateur(patient40).
autreoperateur(patient55).
autreoperateur(patient58).
autreoperateur(patient69).
autreoperateur(patient71).
autreoperateur(patient76).
autreoperateur(patient77).
autreoperateur(patient79).
autreoperateur(patient81).
autreoperateur(patient82).
autreoperateur(patient83).
autreoperateur(patient87).
autreoperateur(patient88).
autreoperateur(patient92).
autreoperateur(patient103).
autreoperateur(patient104).
autreoperateur(patient117).
dureeintubation(patient38).
dureeintubation(patient67).
dureeintubation(patient76).
dureeintubation(patient77).
dureeintubation(patient84).
dureeintubation(patient90).
dureeintubation(patient94).
dureeintubation(patient103).
eichman(patient3).
eichman(patient5).
eichman(patient6).
eichman(patient7).
eichman(patient8).
eichman(patient11).
eichman(patient13).
eichman(patient16).
eichman(patient17).
eichman(patient19).
eichman(patient20).
eichman(patient21).
eichman(patient31).
eichman(patient37).
eichman(patient69).
eichman(patient71).
eichman(patient83).
eichman(patient96).
eichman(patient112).
eichman(patient117).
eichman(patient118).
moyensupraglottique(patient16).
moyensupraglottique(patient83).
intubationdifficile(patient3).
intubationdifficile(patient5).
intubationdifficile(patient6).
intubationdifficile(patient7).
intubationdifficile(patient8).
intubationdifficile(patient11).
intubationdifficile(patient13).
intubationdifficile(patient16).
intubationdifficile(patient19).
intubationdifficile(patient20).
intubationdifficile(patient21).
intubationdifficile(patient31).
intubationdifficile(patient37).
intubationdifficile(patient65).
intubationdifficile(patient69).
intubationdifficile(patient71).
intubationdifficile(patient77).
intubationdifficile(patient82).
intubationdifficile(patient83).
intubationdifficile(patient96).
intubationdifficile(patient104).
intubationdifficile(patient112).
intubationdifficile(patient117).
intubationdifficile(patient118).
hypotention(patient4).
hypotention(patient6).
hypotention(patient7).
hypotention(patient8).
hypotention(patient9).
hypotention(patient10).
hypotention(patient16).
hypotention(patient18).
hypotention(patient21).
hypotention(patient22).
hypotention(patient27).
hypotention(patient30).
hypotention(patient31).
hypotention(patient35).
hypotention(patient42).
hypotention(patient45).
hypotention(patient55).
hypotention(patient58).
hypotention(patient60).
hypotention(patient64).
hypotention(patient70).
hypotention(patient73).
hypotention(patient80).
hypotention(patient81).
hypotention(patient82).
hypotention(patient88).
hypotention(patient91).
hypotention(patient92).
hypotention(patient93).
hypotention(patient95).
hypotention(patient99).
hypotention(patient115).
desaturation(patient5).
desaturation(patient6).
desaturation(patient7).
desaturation(patient8).
desaturation(patient9).
desaturation(patient10).
desaturation(patient14).
desaturation(patient15).
desaturation(patient16).
desaturation(patient20).
desaturation(patient22).
desaturation(patient27).
desaturation(patient28).
desaturation(patient31).
desaturation(patient35).
desaturation(patient37).
desaturation(patient40).
desaturation(patient43).
desaturation(patient45).
desaturation(patient50).
desaturation(patient58).
desaturation(patient64).
desaturation(patient65).
desaturation(patient69).
desaturation(patient70).
desaturation(patient71).
desaturation(patient72).
desaturation(patient74).
desaturation(patient81).
desaturation(patient82).
desaturation(patient83).
desaturation(patient86).
desaturation(patient87).
desaturation(patient88).
desaturation(patient89).
desaturation(patient90).
desaturation(patient93).
desaturation(patient94).
desaturation(patient103).
desaturation(patient104).
desaturation(patient112).
desaturation(patient115).
desaturation(patient117).
fracturedentaire(patient20).
arret(patient2).
arret(patient3).
arret(patient4).
arret(patient5).
arret(patient7).
arret(patient9).
arret(patient11).
arret(patient13).
arret(patient14).
arret(patient15).
arret(patient16).
arret(patient17).
arret(patient19).
arret(patient20).
arret(patient22).
arret(patient25).
arret(patient26).
arret(patient28).
arret(patient33).
arret(patient36).
arret(patient37).
arret(patient54).
arret(patient64).
arret(patient69).
arret(patient80).
arret(patient81).
arret(patient87).
arret(patient88).
arret(patient99).
arret(patient116).
arret(patient117).
bradycardie(patient7).
bradycardie(patient10).
bradycardie(patient66).
bradycardie(patient72).
bradycardie(patient93).
bradycardie(patient116).
intubationselective(patient16).
intubationselective(patient52).
intubationselective(patient67).
intubationselective(patient83).
intubationoesophagienne(patient16).
intubationoesophagienne(patient58).
intubationoesophagienne(patient69).
intubationoesophagienne(patient82).
intubationoesophagienne(patient83).
intubationoesophagienne(patient103).
extubation(patient8).
extubation(patient23).
complications(patient2).
complications(patient3).
complications(patient4).
complications(patient5).
complications(patient6).
complications(patient7).
complications(patient8).
complications(patient9).
complications(patient10).
complications(patient11).
complications(patient13).
complications(patient14).
complications(patient15).
complications(patient16).
complications(patient17).
complications(patient18).
complications(patient19).
complications(patient20).
complications(patient21).
complications(patient22).
complications(patient23).
complications(patient25).
complications(patient26).
complications(patient27).
complications(patient28).
complications(patient30).
complications(patient31).
complications(patient33).
complications(patient35).
complications(patient36).
complications(patient37).
complications(patient40).
complications(patient42).
complications(patient43).
complications(patient45).
complications(patient50).
complications(patient52).
complications(patient54).
complications(patient55).
complications(patient58).
complications(patient60).
complications(patient64).
complications(patient65).
complications(patient66).
complications(patient67).
complications(patient69).
complications(patient70).
complications(patient71).
complications(patient72).
complications(patient73).
complications(patient74).
complications(patient80).
complications(patient81).
complications(patient82).
complications(patient83).
complications(patient86).
complications(patient87).
complications(patient88).
complications(patient89).
complications(patient90).
complications(patient91).
complications(patient92).
complications(patient93).
complications(patient94).
complications(patient95).
complications(patient99).
complications(patient103).
complications(patient104).
complications(patient112).
complications(patient115).
complications(patient116).
complications(patient117).
:- end_bg.

:- begin_in_pos.
complication(patient4,hypotention).
complication(patient6,hypotention).
complication(patient7,hypotention).
complication(patient8,hypotention).
complication(patient9,hypotention).
complication(patient10,hypotention).
complication(patient16,hypotention).
complication(patient18,hypotention).
complication(patient21,hypotention).
complication(patient22,hypotention).
complication(patient27,hypotention).
complication(patient30,hypotention).
complication(patient31,hypotention).
complication(patient35,hypotention).
complication(patient42,hypotention).
complication(patient45,hypotention).
complication(patient55,hypotention).
complication(patient58,hypotention).
complication(patient60,hypotention).
complication(patient64,hypotention).
complication(patient70,hypotention).
complication(patient73,hypotention).
complication(patient80,hypotention).
complication(patient81,hypotention).
complication(patient82,hypotention).
complication(patient88,hypotention).
complication(patient91,hypotention).
complication(patient92,hypotention).
complication(patient93,hypotention).
complication(patient95,hypotention).
complication(patient99,hypotention).
complication(patient115,hypotention).
complication(patient5,desaturation).
complication(patient6,desaturation).
complication(patient7,desaturation).
complication(patient8,desaturation).
complication(patient9,desaturation).
complication(patient10,desaturation).
complication(patient14,desaturation).
complication(patient15,desaturation).
complication(patient16,desaturation).
complication(patient20,desaturation).
complication(patient22,desaturation).
complication(patient27,desaturation).
complication(patient28,desaturation).
complication(patient31,desaturation).
complication(patient35,desaturation).
complication(patient37,desaturation).
complication(patient40,desaturation).
complication(patient43,desaturation).
complication(patient45,desaturation).
complication(patient50,desaturation).
complication(patient58,desaturation).
complication(patient64,desaturation).
complication(patient65,desaturation).
complication(patient69,desaturation).
complication(patient70,desaturation).
complication(patient71,desaturation).
complication(patient72,desaturation).
complication(patient74,desaturation).
complication(patient81,desaturation).
complication(patient82,desaturation).
complication(patient83,desaturation).
complication(patient86,desaturation).
complication(patient87,desaturation).
complication(patient88,desaturation).
complication(patient89,desaturation).
complication(patient90,desaturation).
complication(patient93,desaturation).
complication(patient94,desaturation).
complication(patient103,desaturation).
complication(patient104,desaturation).
complication(patient112,desaturation).
complication(patient115,desaturation).
complication(patient117,desaturation).
complication(patient20,fracturedentaire).
complication(patient7,bradycardie).
complication(patient10,bradycardie).
complication(patient66,bradycardie).
complication(patient72,bradycardie).
complication(patient93,bradycardie).
complication(patient116,bradycardie).
complication(patient16,intubationselective).
complication(patient52,intubationselective).
complication(patient67,intubationselective).
complication(patient83,intubationselective).
complication(patient8,extubation).
complication(patient23,extubation).
complication(patient2,arret).
complication(patient3,arret).
complication(patient4,arret).
complication(patient5,arret).
complication(patient7,arret).
complication(patient9,arret).
complication(patient11,arret).
complication(patient13,arret).
complication(patient14,arret).
complication(patient15,arret).
complication(patient16,arret).
complication(patient17,arret).
complication(patient19,arret).
complication(patient20,arret).
complication(patient22,arret).
complication(patient25,arret).
complication(patient26,arret).
complication(patient28,arret).
complication(patient33,arret).
complication(patient36,arret).
complication(patient37,arret).
complication(patient54,arret).
complication(patient64,arret).
complication(patient69,arret).
complication(patient80,arret).
complication(patient81,arret).
complication(patient87,arret).
complication(patient88,arret).
complication(patient99,arret).
complication(patient116,arret).
complication(patient117,arret).
:- end_in_pos.

:- begin_in_neg.
complication(patient1,hypotention).
complication(patient2,hypotention).
complication(patient3,hypotention).
complication(patient5,hypotention).
complication(patient11,hypotention).
complication(patient12,hypotention).
complication(patient13,hypotention).
complication(patient14,hypotention).
complication(patient15,hypotention).
complication(patient17,hypotention).
complication(patient19,hypotention).
complication(patient20,hypotention).
complication(patient23,hypotention).
complication(patient24,hypotention).
complication(patient25,hypotention).
complication(patient26,hypotention).
complication(patient28,hypotention).
complication(patient29,hypotention).
complication(patient32,hypotention).
complication(patient33,hypotention).
complication(patient34,hypotention).
complication(patient36,hypotention).
complication(patient37,hypotention).
complication(patient38,hypotention).
complication(patient39,hypotention).
complication(patient40,hypotention).
complication(patient41,hypotention).
complication(patient43,hypotention).
complication(patient44,hypotention).
complication(patient46,hypotention).
complication(patient47,hypotention).
complication(patient48,hypotention).
complication(patient49,hypotention).
complication(patient50,hypotention).
complication(patient51,hypotention).
complication(patient52,hypotention).
complication(patient53,hypotention).
complication(patient54,hypotention).
complication(patient56,hypotention).
complication(patient57,hypotention).
complication(patient59,hypotention).
complication(patient61,hypotention).
complication(patient62,hypotention).
complication(patient63,hypotention).
complication(patient65,hypotention).
complication(patient66,hypotention).
complication(patient67,hypotention).
complication(patient68,hypotention).
complication(patient69,hypotention).
complication(patient71,hypotention).
complication(patient72,hypotention).
complication(patient74,hypotention).
complication(patient75,hypotention).
complication(patient76,hypotention).
complication(patient77,hypotention).
complication(patient78,hypotention).
complication(patient79,hypotention).
complication(patient83,hypotention).
complication(patient84,hypotention).
complication(patient85,hypotention).
complication(patient86,hypotention).
complication(patient87,hypotention).
complication(patient89,hypotention).
complication(patient90,hypotention).
complication(patient94,hypotention).
complication(patient96,hypotention).
complication(patient97,hypotention).
complication(patient98,hypotention).
complication(patient100,hypotention).
complication(patient101,hypotention).
complication(patient102,hypotention).
complication(patient103,hypotention).
complication(patient104,hypotention).
complication(patient105,hypotention).
complication(patient106,hypotention).
complication(patient107,hypotention).
complication(patient108,hypotention).
complication(patient109,hypotention).
complication(patient110,hypotention).
complication(patient111,hypotention).
complication(patient112,hypotention).
complication(patient113,hypotention).
complication(patient114,hypotention).
complication(patient116,hypotention).
complication(patient117,hypotention).
complication(patient118,hypotention).
complication(patient1,desaturation).
complication(patient2,desaturation).
complication(patient3,desaturation).
complication(patient4,desaturation).
complication(patient11,desaturation).
complication(patient12,desaturation).
complication(patient13,desaturation).
complication(patient17,desaturation).
complication(patient18,desaturation).
complication(patient19,desaturation).
complication(patient21,desaturation).
complication(patient23,desaturation).
complication(patient24,desaturation).
complication(patient25,desaturation).
complication(patient26,desaturation).
complication(patient29,desaturation).
complication(patient30,desaturation).
complication(patient32,desaturation).
complication(patient33,desaturation).
complication(patient34,desaturation).
complication(patient36,desaturation).
complication(patient38,desaturation).
complication(patient39,desaturation).
complication(patient41,desaturation).
complication(patient42,desaturation).
complication(patient44,desaturation).
complication(patient46,desaturation).
complication(patient47,desaturation).
complication(patient48,desaturation).
complication(patient49,desaturation).
complication(patient51,desaturation).
complication(patient52,desaturation).
complication(patient53,desaturation).
complication(patient54,desaturation).
complication(patient55,desaturation).
complication(patient56,desaturation).
complication(patient57,desaturation).
complication(patient59,desaturation).
complication(patient60,desaturation).
complication(patient61,desaturation).
complication(patient62,desaturation).
complication(patient63,desaturation).
complication(patient66,desaturation).
complication(patient67,desaturation).
complication(patient68,desaturation).
complication(patient73,desaturation).
complication(patient75,desaturation).
complication(patient76,desaturation).
complication(patient77,desaturation).
complication(patient78,desaturation).
complication(patient79,desaturation).
complication(patient80,desaturation).
complication(patient84,desaturation).
complication(patient85,desaturation).
complication(patient91,desaturation).
complication(patient92,desaturation).
complication(patient95,desaturation).
complication(patient96,desaturation).
complication(patient97,desaturation).
complication(patient98,desaturation).
complication(patient99,desaturation).
complication(patient100,desaturation).
complication(patient101,desaturation).
complication(patient102,desaturation).
complication(patient105,desaturation).
complication(patient106,desaturation).
complication(patient107,desaturation).
complication(patient108,desaturation).
complication(patient109,desaturation).
complication(patient110,desaturation).
complication(patient111,desaturation).
complication(patient113,desaturation).
complication(patient114,desaturation).
complication(patient116,desaturation).
complication(patient118,desaturation).
complication(patient1,fracturedentaire).
complication(patient2,fracturedentaire).
complication(patient3,fracturedentaire).
complication(patient4,fracturedentaire).
complication(patient5,fracturedentaire).
complication(patient6,fracturedentaire).
complication(patient7,fracturedentaire).
complication(patient8,fracturedentaire).
complication(patient9,fracturedentaire).
complication(patient10,fracturedentaire).
complication(patient11,fracturedentaire).
complication(patient12,fracturedentaire).
complication(patient13,fracturedentaire).
complication(patient14,fracturedentaire).
complication(patient15,fracturedentaire).
complication(patient16,fracturedentaire).
complication(patient17,fracturedentaire).
complication(patient18,fracturedentaire).
complication(patient19,fracturedentaire).
complication(patient21,fracturedentaire).
complication(patient22,fracturedentaire).
complication(patient23,fracturedentaire).
complication(patient24,fracturedentaire).
complication(patient25,fracturedentaire).
complication(patient26,fracturedentaire).
complication(patient27,fracturedentaire).
complication(patient28,fracturedentaire).
complication(patient29,fracturedentaire).
complication(patient30,fracturedentaire).
complication(patient31,fracturedentaire).
complication(patient32,fracturedentaire).
complication(patient33,fracturedentaire).
complication(patient34,fracturedentaire).
complication(patient35,fracturedentaire).
complication(patient36,fracturedentaire).
complication(patient37,fracturedentaire).
complication(patient38,fracturedentaire).
complication(patient39,fracturedentaire).
complication(patient40,fracturedentaire).
complication(patient41,fracturedentaire).
complication(patient42,fracturedentaire).
complication(patient43,fracturedentaire).
complication(patient44,fracturedentaire).
complication(patient45,fracturedentaire).
complication(patient46,fracturedentaire).
complication(patient47,fracturedentaire).
complication(patient48,fracturedentaire).
complication(patient49,fracturedentaire).
complication(patient50,fracturedentaire).
complication(patient51,fracturedentaire).
complication(patient52,fracturedentaire).
complication(patient53,fracturedentaire).
complication(patient54,fracturedentaire).
complication(patient55,fracturedentaire).
complication(patient56,fracturedentaire).
complication(patient57,fracturedentaire).
complication(patient58,fracturedentaire).
complication(patient59,fracturedentaire).
complication(patient60,fracturedentaire).
complication(patient61,fracturedentaire).
complication(patient62,fracturedentaire).
complication(patient63,fracturedentaire).
complication(patient64,fracturedentaire).
complication(patient65,fracturedentaire).
complication(patient66,fracturedentaire).
complication(patient67,fracturedentaire).
complication(patient68,fracturedentaire).
complication(patient69,fracturedentaire).
complication(patient70,fracturedentaire).
complication(patient71,fracturedentaire).
complication(patient72,fracturedentaire).
complication(patient73,fracturedentaire).
complication(patient74,fracturedentaire).
complication(patient75,fracturedentaire).
complication(patient76,fracturedentaire).
complication(patient77,fracturedentaire).
complication(patient78,fracturedentaire).
complication(patient79,fracturedentaire).
complication(patient80,fracturedentaire).
complication(patient81,fracturedentaire).
complication(patient82,fracturedentaire).
complication(patient83,fracturedentaire).
complication(patient84,fracturedentaire).
complication(patient85,fracturedentaire).
complication(patient86,fracturedentaire).
complication(patient87,fracturedentaire).
complication(patient88,fracturedentaire).
complication(patient89,fracturedentaire).
complication(patient90,fracturedentaire).
complication(patient91,fracturedentaire).
complication(patient92,fracturedentaire).
complication(patient93,fracturedentaire).
complication(patient94,fracturedentaire).
complication(patient95,fracturedentaire).
complication(patient96,fracturedentaire).
complication(patient97,fracturedentaire).
complication(patient98,fracturedentaire).
complication(patient99,fracturedentaire).
complication(patient100,fracturedentaire).
complication(patient101,fracturedentaire).
complication(patient102,fracturedentaire).
complication(patient103,fracturedentaire).
complication(patient104,fracturedentaire).
complication(patient105,fracturedentaire).
complication(patient106,fracturedentaire).
complication(patient107,fracturedentaire).
complication(patient108,fracturedentaire).
complication(patient109,fracturedentaire).
complication(patient110,fracturedentaire).
complication(patient111,fracturedentaire).
complication(patient112,fracturedentaire).
complication(patient113,fracturedentaire).
complication(patient114,fracturedentaire).
complication(patient115,fracturedentaire).
complication(patient116,fracturedentaire).
complication(patient117,fracturedentaire).
complication(patient118,fracturedentaire).
complication(patient1,bradycardie).
complication(patient2,bradycardie).
complication(patient3,bradycardie).
complication(patient4,bradycardie).
complication(patient5,bradycardie).
complication(patient6,bradycardie).
complication(patient8,bradycardie).
complication(patient9,bradycardie).
complication(patient11,bradycardie).
complication(patient12,bradycardie).
complication(patient13,bradycardie).
complication(patient14,bradycardie).
complication(patient15,bradycardie).
complication(patient16,bradycardie).
complication(patient17,bradycardie).
complication(patient18,bradycardie).
complication(patient19,bradycardie).
complication(patient20,bradycardie).
complication(patient21,bradycardie).
complication(patient22,bradycardie).
complication(patient23,bradycardie).
complication(patient24,bradycardie).
complication(patient25,bradycardie).
complication(patient26,bradycardie).
complication(patient27,bradycardie).
complication(patient28,bradycardie).
complication(patient29,bradycardie).
complication(patient30,bradycardie).
complication(patient31,bradycardie).
complication(patient32,bradycardie).
complication(patient33,bradycardie).
complication(patient34,bradycardie).
complication(patient35,bradycardie).
complication(patient36,bradycardie).
complication(patient37,bradycardie).
complication(patient38,bradycardie).
complication(patient39,bradycardie).
complication(patient40,bradycardie).
complication(patient41,bradycardie).
complication(patient42,bradycardie).
complication(patient43,bradycardie).
complication(patient44,bradycardie).
complication(patient45,bradycardie).
complication(patient46,bradycardie).
complication(patient47,bradycardie).
complication(patient48,bradycardie).
complication(patient49,bradycardie).
complication(patient50,bradycardie).
complication(patient51,bradycardie).
complication(patient52,bradycardie).
complication(patient53,bradycardie).
complication(patient54,bradycardie).
complication(patient55,bradycardie).
complication(patient56,bradycardie).
complication(patient57,bradycardie).
complication(patient58,bradycardie).
complication(patient59,bradycardie).
complication(patient60,bradycardie).
complication(patient61,bradycardie).
complication(patient62,bradycardie).
complication(patient63,bradycardie).
complication(patient64,bradycardie).
complication(patient65,bradycardie).
complication(patient67,bradycardie).
complication(patient68,bradycardie).
complication(patient69,bradycardie).
complication(patient70,bradycardie).
complication(patient71,bradycardie).
complication(patient73,bradycardie).
complication(patient74,bradycardie).
complication(patient75,bradycardie).
complication(patient76,bradycardie).
complication(patient77,bradycardie).
complication(patient78,bradycardie).
complication(patient79,bradycardie).
complication(patient80,bradycardie).
complication(patient81,bradycardie).
complication(patient82,bradycardie).
complication(patient83,bradycardie).
complication(patient84,bradycardie).
complication(patient85,bradycardie).
complication(patient86,bradycardie).
complication(patient87,bradycardie).
complication(patient88,bradycardie).
complication(patient89,bradycardie).
complication(patient90,bradycardie).
complication(patient91,bradycardie).
complication(patient92,bradycardie).
complication(patient94,bradycardie).
complication(patient95,bradycardie).
complication(patient96,bradycardie).
complication(patient97,bradycardie).
complication(patient98,bradycardie).
complication(patient99,bradycardie).
complication(patient100,bradycardie).
complication(patient101,bradycardie).
complication(patient102,bradycardie).
complication(patient103,bradycardie).
complication(patient104,bradycardie).
complication(patient105,bradycardie).
complication(patient106,bradycardie).
complication(patient107,bradycardie).
complication(patient108,bradycardie).
complication(patient109,bradycardie).
complication(patient110,bradycardie).
complication(patient111,bradycardie).
complication(patient112,bradycardie).
complication(patient113,bradycardie).
complication(patient114,bradycardie).
complication(patient115,bradycardie).
complication(patient117,bradycardie).
complication(patient118,bradycardie).
complication(patient1,intubationselective).
complication(patient2,intubationselective).
complication(patient3,intubationselective).
complication(patient4,intubationselective).
complication(patient5,intubationselective).
complication(patient6,intubationselective).
complication(patient7,intubationselective).
complication(patient8,intubationselective).
complication(patient9,intubationselective).
complication(patient10,intubationselective).
complication(patient11,intubationselective).
complication(patient12,intubationselective).
complication(patient13,intubationselective).
complication(patient14,intubationselective).
complication(patient15,intubationselective).
complication(patient17,intubationselective).
complication(patient18,intubationselective).
complication(patient19,intubationselective).
complication(patient20,intubationselective).
complication(patient21,intubationselective).
complication(patient22,intubationselective).
complication(patient23,intubationselective).
complication(patient24,intubationselective).
complication(patient25,intubationselective).
complication(patient26,intubationselective).
complication(patient27,intubationselective).
complication(patient28,intubationselective).
complication(patient29,intubationselective).
complication(patient30,intubationselective).
complication(patient31,intubationselective).
complication(patient32,intubationselective).
complication(patient33,intubationselective).
complication(patient34,intubationselective).
complication(patient35,intubationselective).
complication(patient36,intubationselective).
complication(patient37,intubationselective).
complication(patient38,intubationselective).
complication(patient39,intubationselective).
complication(patient40,intubationselective).
complication(patient41,intubationselective).
complication(patient42,intubationselective).
complication(patient43,intubationselective).
complication(patient44,intubationselective).
complication(patient45,intubationselective).
complication(patient46,intubationselective).
complication(patient47,intubationselective).
complication(patient48,intubationselective).
complication(patient49,intubationselective).
complication(patient50,intubationselective).
complication(patient51,intubationselective).
complication(patient53,intubationselective).
complication(patient54,intubationselective).
complication(patient55,intubationselective).
complication(patient56,intubationselective).
complication(patient57,intubationselective).
complication(patient58,intubationselective).
complication(patient59,intubationselective).
complication(patient60,intubationselective).
complication(patient61,intubationselective).
complication(patient62,intubationselective).
complication(patient63,intubationselective).
complication(patient64,intubationselective).
complication(patient65,intubationselective).
complication(patient66,intubationselective).
complication(patient68,intubationselective).
complication(patient69,intubationselective).
complication(patient70,intubationselective).
complication(patient71,intubationselective).
complication(patient72,intubationselective).
complication(patient73,intubationselective).
complication(patient74,intubationselective).
complication(patient75,intubationselective).
complication(patient76,intubationselective).
complication(patient77,intubationselective).
complication(patient78,intubationselective).
complication(patient79,intubationselective).
complication(patient80,intubationselective).
complication(patient81,intubationselective).
complication(patient82,intubationselective).
complication(patient84,intubationselective).
complication(patient85,intubationselective).
complication(patient86,intubationselective).
complication(patient87,intubationselective).
complication(patient88,intubationselective).
complication(patient89,intubationselective).
complication(patient90,intubationselective).
complication(patient91,intubationselective).
complication(patient92,intubationselective).
complication(patient93,intubationselective).
complication(patient94,intubationselective).
complication(patient95,intubationselective).
complication(patient96,intubationselective).
complication(patient97,intubationselective).
complication(patient98,intubationselective).
complication(patient99,intubationselective).
complication(patient100,intubationselective).
complication(patient101,intubationselective).
complication(patient102,intubationselective).
complication(patient103,intubationselective).
complication(patient104,intubationselective).
complication(patient105,intubationselective).
complication(patient106,intubationselective).
complication(patient107,intubationselective).
complication(patient108,intubationselective).
complication(patient109,intubationselective).
complication(patient110,intubationselective).
complication(patient111,intubationselective).
complication(patient112,intubationselective).
complication(patient113,intubationselective).
complication(patient114,intubationselective).
complication(patient115,intubationselective).
complication(patient116,intubationselective).
complication(patient117,intubationselective).
complication(patient118,intubationselective).
complication(patient1,extubation).
complication(patient2,extubation).
complication(patient3,extubation).
complication(patient4,extubation).
complication(patient5,extubation).
complication(patient6,extubation).
complication(patient7,extubation).
complication(patient9,extubation).
complication(patient10,extubation).
complication(patient11,extubation).
complication(patient12,extubation).
complication(patient13,extubation).
complication(patient14,extubation).
complication(patient15,extubation).
complication(patient16,extubation).
complication(patient17,extubation).
complication(patient18,extubation).
complication(patient19,extubation).
complication(patient20,extubation).
complication(patient21,extubation).
complication(patient22,extubation).
complication(patient24,extubation).
complication(patient25,extubation).
complication(patient26,extubation).
complication(patient27,extubation).
complication(patient28,extubation).
complication(patient29,extubation).
complication(patient30,extubation).
complication(patient31,extubation).
complication(patient32,extubation).
complication(patient33,extubation).
complication(patient34,extubation).
complication(patient35,extubation).
complication(patient36,extubation).
complication(patient37,extubation).
complication(patient38,extubation).
complication(patient39,extubation).
complication(patient40,extubation).
complication(patient41,extubation).
complication(patient42,extubation).
complication(patient43,extubation).
complication(patient44,extubation).
complication(patient45,extubation).
complication(patient46,extubation).
complication(patient47,extubation).
complication(patient48,extubation).
complication(patient49,extubation).
complication(patient50,extubation).
complication(patient51,extubation).
complication(patient52,extubation).
complication(patient53,extubation).
complication(patient54,extubation).
complication(patient55,extubation).
complication(patient56,extubation).
complication(patient57,extubation).
complication(patient58,extubation).
complication(patient59,extubation).
complication(patient60,extubation).
complication(patient61,extubation).
complication(patient62,extubation).
complication(patient63,extubation).
complication(patient64,extubation).
complication(patient65,extubation).
complication(patient66,extubation).
complication(patient67,extubation).
complication(patient68,extubation).
complication(patient69,extubation).
complication(patient70,extubation).
complication(patient71,extubation).
complication(patient72,extubation).
complication(patient73,extubation).
complication(patient74,extubation).
complication(patient75,extubation).
complication(patient76,extubation).
complication(patient77,extubation).
complication(patient78,extubation).
complication(patient79,extubation).
complication(patient80,extubation).
complication(patient81,extubation).
complication(patient82,extubation).
complication(patient83,extubation).
complication(patient84,extubation).
complication(patient85,extubation).
complication(patient86,extubation).
complication(patient87,extubation).
complication(patient88,extubation).
complication(patient89,extubation).
complication(patient90,extubation).
complication(patient91,extubation).
complication(patient92,extubation).
complication(patient93,extubation).
complication(patient94,extubation).
complication(patient95,extubation).
complication(patient96,extubation).
complication(patient97,extubation).
complication(patient98,extubation).
complication(patient99,extubation).
complication(patient100,extubation).
complication(patient101,extubation).
complication(patient102,extubation).
complication(patient103,extubation).
complication(patient104,extubation).
complication(patient105,extubation).
complication(patient106,extubation).
complication(patient107,extubation).
complication(patient108,extubation).
complication(patient109,extubation).
complication(patient110,extubation).
complication(patient111,extubation).
complication(patient112,extubation).
complication(patient113,extubation).
complication(patient114,extubation).
complication(patient115,extubation).
complication(patient116,extubation).
complication(patient117,extubation).
complication(patient118,extubation).
complication(patient1,arret).
complication(patient6,arret).
complication(patient8,arret).
complication(patient10,arret).
complication(patient12,arret).
complication(patient18,arret).
complication(patient21,arret).
complication(patient23,arret).
complication(patient24,arret).
complication(patient27,arret).
complication(patient29,arret).
complication(patient30,arret).
complication(patient31,arret).
complication(patient32,arret).
complication(patient34,arret).
complication(patient35,arret).
complication(patient38,arret).
complication(patient39,arret).
complication(patient40,arret).
complication(patient41,arret).
complication(patient42,arret).
complication(patient43,arret).
complication(patient44,arret).
complication(patient45,arret).
complication(patient46,arret).
complication(patient47,arret).
complication(patient48,arret).
complication(patient49,arret).
complication(patient50,arret).
complication(patient51,arret).
complication(patient52,arret).
complication(patient53,arret).
complication(patient55,arret).
complication(patient56,arret).
complication(patient57,arret).
complication(patient58,arret).
complication(patient59,arret).
complication(patient60,arret).
complication(patient61,arret).
complication(patient62,arret).
complication(patient63,arret).
complication(patient65,arret).
complication(patient66,arret).
complication(patient67,arret).
complication(patient68,arret).
complication(patient70,arret).
complication(patient71,arret).
complication(patient72,arret).
complication(patient73,arret).
complication(patient74,arret).
complication(patient75,arret).
complication(patient76,arret).
complication(patient77,arret).
complication(patient78,arret).
complication(patient79,arret).
complication(patient82,arret).
complication(patient83,arret).
complication(patient84,arret).
complication(patient85,arret).
complication(patient86,arret).
complication(patient89,arret).
complication(patient90,arret).
complication(patient91,arret).
complication(patient92,arret).
complication(patient93,arret).
complication(patient94,arret).
complication(patient95,arret).
complication(patient96,arret).
complication(patient97,arret).
complication(patient98,arret).
complication(patient100,arret).
complication(patient101,arret).
complication(patient102,arret).
complication(patient103,arret).
complication(patient104,arret).
complication(patient105,arret).
complication(patient106,arret).
complication(patient107,arret).
complication(patient108,arret).
complication(patient109,arret).
complication(patient110,arret).
complication(patient111,arret).
complication(patient112,arret).
complication(patient113,arret).
complication(patient114,arret).
complication(patient115,arret).
complication(patient118,arret).
:- end_in_neg.
