modeh(1,complication(+patient)).
modeb(*,experience(+patient)).
modeb(*,hypertension(+patient)).
modeb(*,diabetes(+patient)).
modeb(*,copd(+patient)).
modeb(*,asthma(+patient)).
modeb(*,coronary_artery_disease(+patient)).
modeb(*,other_conditions(+patient)).
modeb(*,ic(+patient)).
modeb(*,indication(+patient)).
modeb(*,diagnostic(+patient)).
modeb(*,patientobese(+patient)).
modeb(*,high_arched_palate(+patient)).
modeb(*,shortneck(+patient)).
modeb(*,necktrauma(+patient)).
modeb(*,beardormoustache(+patient)).
modeb(*,largetongue(+patient)).
modeb(*,openingmouth(+patient)).
modeb(*,thyromentaldistance(+patient)).
modeb(*,betweenhyoidboneandthyroid(+patient)).
modeb(*,tumor(+patient)).
modeb(*,epiglottitis(+patient)).
modeb(*,recentnecksurgery(+patient)).
modeb(*,hematoma(+patient)).
modeb(*,cervicalcollar(+patient)).
modeb(*,elderly(+patient)).
modeb(*,numerosonde(+patient)).
modeb(*,laryngodifficile(+patient)).
modeb(*,nombretentatives(+patient)).
modeb(*,autreoperateur(+patient)).
modeb(*,eichman(+patient)).
modeb(*,moyensupraglottique(+patient)).
modeb(*,intubationdifficile(+patient)).

modeb(*,extubation(+patient)).
modeb(*,lemonscore(+patient,+score)).
modeb(*,cormack(+patient,+score)).

determination(complication/1,experience/1).
determination(complication/1,hypertension/1).
determination(complication/1,diabetes/1).
determination(complication/1,copd/1).
determination(complication/1,asthma/1).
determination(complication/1,coronary_artery_disease/1).
determination(complication/1,other_conditions/1).
determination(complication/1,ic/1).
determination(complication/1,indication/1).
determination(complication/1,diagnostic/1).
determination(complication/1,patientobese/1).
determination(complication/1,high_arched_palate/1).
determination(complication/1,shortneck/1).
determination(complication/1,necktrauma/1).
determination(complication/1,beardormoustache/1).
determination(complication/1,largetongue/1).
determination(complication/1,openingmouth/1).
determination(complication/1,thyromentaldistance/1).
determination(complication/1,betweenhyoidboneandthyroid/1).
determination(complication/1,tumor/1).
determination(complication/1,epiglottitis/1).
determination(complication/1,recentnecksurgery/1).
determination(complication/1,hematoma/1).
determination(complication/1,cervicalcollar/1).
determination(complication/1,elderly/1).
determination(complication/1,numerosonde/1).
determination(complication/1,laryngodifficile/1).
determination(complication/1,nombretentatives/1).
determination(complication/1,autreoperateur/1).
determination(complication/1,eichman/1).
determination(complication/1,moyensupraglottique/1).
determination(complication/1,intubationdifficile/1).


determination(complication/1,extubation/1).
determination(complication/1,lemonscore/2).
determination(complication/1,cormack/2).

:- begin_bg.
patient(patient6).
hypertension(patient6).
copd(patient6).
patientobese(patient6).
shortneck(patient6).
largetongue(patient6).
openingmouth(patient6).
thyromentaldistance(patient6).
recentnecksurgery(patient6).
autreoperateur(patient6).
eichman(patient6).
intubationdifficile(patient6).
lemonscore(patient6,6).
cormack(patient6,2).
hard_intubation(patient6).
patient(patient93).
hypertension(patient93).
lemonscore(patient93,1).
cormack(patient93,0).
patient(patient21).
experience(patient21).
hypertension(patient21).
diabetes(patient21).
patientobese(patient21).
shortneck(patient21).
openingmouth(patient21).
elderly(patient21).
eichman(patient21).
intubationdifficile(patient21).
lemonscore(patient21,4).
cormack(patient21,2).
patient(patient2).
largetongue(patient2).
laryngodifficile(patient2).
cardiac_arrest(patient2).
lemonscore(patient2,0).
cormack(patient2,3).
hardlaryngo(patient2).
patient(patient35).
experience(patient35).
lemonscore(patient35,1).
cormack(patient35,0).
patient(patient74).
diabetes(patient74).
patientobese(patient74).
shortneck(patient74).
lemonscore(patient74,0).
cormack(patient74,0).
patient(patient13).
eichman(patient13).
intubationdifficile(patient13).
cardiac_arrest(patient13).
lemonscore(patient13,1).
cormack(patient13,2).
patient(patient45).
coronary_artery_disease(patient45).
elderly(patient45).
lemonscore(patient45,1).
cormack(patient45,0).
patient(patient15).
experience(patient15).
hypertension(patient15).
copd(patient15).
patientobese(patient15).
shortneck(patient15).
largetongue(patient15).
laryngodifficile(patient15).
lemonscore(patient15,3).
cormack(patient15,3).
hardlaryngo(patient15).
patient(patient83).
hypertension(patient83).
high_arched_palate(patient83).
openingmouth(patient83).
laryngodifficile(patient83).
autreoperateur(patient83).
eichman(patient83).
moyensupraglottique(patient83).
intubationdifficile(patient83).

lemonscore(patient83,0).
cormack(patient83,4).
hardlaryngo(patient83).
patient(patient71).
thyromentaldistance(patient71).
laryngodifficile(patient71).
autreoperateur(patient71).
eichman(patient71).
intubationdifficile(patient71).
lemonscore(patient71,0).
cormack(patient71,4).
hardlaryngo(patient71).
patient(patient40).
hypertension(patient40).
high_arched_palate(patient40).
openingmouth(patient40).
autreoperateur(patient40).
lemonscore(patient40,2).
cormack(patient40,2).
patient(patient11).
largetongue(patient11).
openingmouth(patient11).
eichman(patient11).
intubationdifficile(patient11).
cardiac_arrest(patient11).
lemonscore(patient11,2).
cormack(patient11,2).
patient(patient69).
shortneck(patient69).
largetongue(patient69).
thyromentaldistance(patient69).
betweenhyoidboneandthyroid(patient69).
laryngodifficile(patient69).
autreoperateur(patient69).
eichman(patient69).
intubationdifficile(patient69).

lemonscore(patient69,4).
cormack(patient69,4).
hardlaryngo(patient69).
patient(patient7).
hypertension(patient7).
beardormoustache(patient7).
largetongue(patient7).
openingmouth(patient7).
thyromentaldistance(patient7).
betweenhyoidboneandthyroid(patient7).
elderly(patient7).
eichman(patient7).
intubationdifficile(patient7).
lemonscore(patient7,6).
cormack(patient7,2).
hard_intubation(patient7).
patient(patient26).
hypertension(patient26).
diabetes(patient26).
patientobese(patient26).
largetongue(patient26).
autreoperateur(patient26).
cardiac_arrest(patient26).
lemonscore(patient26,2).
cormack(patient26,0).
patient(patient87).
hypertension(patient87).
diabetes(patient87).
coronary_artery_disease(patient87).
ic(patient87).
indication(patient87).
shortneck(patient87).
autreoperateur(patient87).
lemonscore(patient87,0).
cormack(patient87,2).
patient(patient73).
experience(patient73).
laryngodifficile(patient73).
lemonscore(patient73,1).
cormack(patient73,3).
hardlaryngo(patient73).
patient(patient43).
experience(patient43).
high_arched_palate(patient43).
lemonscore(patient43,0).
cormack(patient43,2).
patient(patient58).
experience(patient58).
numerosonde(patient58).
laryngodifficile(patient58).
autreoperateur(patient58).
lemonscore(patient58,1).
cormack(patient58,3).
hardlaryngo(patient58).
patient(patient90).
experience(patient90).
hypertension(patient90).
diabetes(patient90).
coronary_artery_disease(patient90).
lemonscore(patient90,1).
cormack(patient90,0).
patient(patient19).
diabetes(patient19).
eichman(patient19).
intubationdifficile(patient19).
cardiac_arrest(patient19).
lemonscore(patient19,1).
cormack(patient19,0).
patient(patient50).
experience(patient50).
lemonscore(patient50,1).
cormack(patient50,0).
patient(patient67).
experience(patient67).
selective_intubation(patient67).
lemonscore(patient67,1).
cormack(patient67,2).
patient(patient108).
patientobese(patient108).
lemonscore(patient108,1).
cormack(patient108,0).
patient(patient77).
hypertension(patient77).
diabetes(patient77).
elderly(patient77).
autreoperateur(patient77).
intubationdifficile(patient77).
lemonscore(patient77,1).
cormack(patient77,0).
patient(patient78).
coronary_artery_disease(patient78).
patientobese(patient78).
high_arched_palate(patient78).
shortneck(patient78).
openingmouth(patient78).
lemonscore(patient78,2).
cormack(patient78,2).
patient(patient114).

hypertension(patient114).
diabetes(patient114).
coronary_artery_disease(patient114).
lemonscore(patient114,1).
cormack(patient114,0).
patient(patient102).
experience(patient102).
patientobese(patient102).
shortneck(patient102).
thyromentaldistance(patient102).
laryngodifficile(patient102).
lemonscore(patient102,2).
cormack(patient102,3).
hardlaryngo(patient102).
patient(patient110).
lemonscore(patient110,1).
cormack(patient110,0).
patient(patient32).
hypertension(patient32).
largetongue(patient32).
lemonscore(patient32,0).
cormack(patient32,0).
patient(patient48).
experience(patient48).
shortneck(patient48).
necktrauma(patient48).
cervicalcollar(patient48).
numerosonde(patient48).
lemonscore(patient48,3).
cormack(patient48,2).
patient(patient41).
experience(patient41).
lemonscore(patient41,1).
cormack(patient41,0).
patient(patient29).
openingmouth(patient29).
lemonscore(patient29,0).
cormack(patient29,0).
patient(patient38).
experience(patient38).
hypertension(patient38).
lemonscore(patient38,1).
cormack(patient38,2).
patient(patient76).
copd(patient76).
autreoperateur(patient76).
lemonscore(patient76,1).
cormack(patient76,0).
patient(patient98).
experience(patient98).
thyromentaldistance(patient98).
lemonscore(patient98,0).
cormack(patient98,2).
patient(patient61).
lemonscore(patient61,1).
cormack(patient61,0).
patient(patient57).
thyromentaldistance(patient57).
lemonscore(patient57,0).
cormack(patient57,0).
:- end_bg.

:- begin_in_pos.
complication(patient6).
complication(patient93).
complication(patient21).
complication(patient2).
complication(patient35).
complication(patient74).
complication(patient13).
complication(patient45).
complication(patient15).
complication(patient83).
complication(patient71).
complication(patient40).
complication(patient11).
complication(patient69).
complication(patient7).
complication(patient26).
complication(patient87).
complication(patient73).
complication(patient43).
complication(patient58).
complication(patient90).
complication(patient19).
complication(patient50).
complication(patient67).
:- end_in_pos.

:- begin_in_neg.
complication(patient108).
complication(patient77).
complication(patient78).
complication(patient114).
complication(patient102).
complication(patient110).
complication(patient32).
complication(patient48).
complication(patient41).
complication(patient29).
complication(patient38).
complication(patient76).
complication(patient98).
complication(patient61).
complication(patient57).
:- end_in_neg.
