modeh(1,complication(+patient)).
modeb(*,experience(+patient)).
modeb(*,hypertension(+patient)).
modeb(*,diabetes(+patient)).
modeb(*,copd(+patient)).
modeb(*,asthma(+patient)).
modeb(*,coronary_artery_disease(+patient)).
modeb(*,other_conditions(+patient)).
modeb(*,ic(+patient)).
modeb(*,indication(+patient)).
modeb(*,diagnostic(+patient)).
modeb(*,patientobese(+patient)).
modeb(*,high_arched_palate(+patient)).
modeb(*,shortneck(+patient)).
modeb(*,necktrauma(+patient)).
modeb(*,beardormoustache(+patient)).
modeb(*,largetongue(+patient)).
modeb(*,openingmouth(+patient)).
modeb(*,thyromentaldistance(+patient)).
modeb(*,betweenhyoidboneandthyroid(+patient)).
modeb(*,tumor(+patient)).
modeb(*,epiglottitis(+patient)).
modeb(*,recentnecksurgery(+patient)).
modeb(*,hematoma(+patient)).
modeb(*,cervicalcollar(+patient)).
modeb(*,elderly(+patient)).
modeb(*,numerosonde(+patient)).
modeb(*,niveaufixation(+patient)).
modeb(*,laryngodifficile(+patient)).
modeb(*,nombretentatives(+patient)).
modeb(*,autreoperateur(+patient)).
modeb(*,intubation_duration(+patient)).
modeb(*,eichman(+patient)).
modeb(*,moyensupraglottique(+patient)).
modeb(*,intubationdifficile(+patient)).
modeb(*,hypotension(+patient)).
modeb(*,desaturation(+patient)).
modeb(*,barotrauma(+patient)).
modeb(*,dental_fracture(+patient)).
modeb(*,cardiac_arrest(+patient)).
modeb(*,bradycardia(+patient)).
modeb(*,selective_intubation(+patient)).
modeb(*,esophageal_intubation(+patient)).
modeb(*,extubation(+patient)).
modeb(*,lemonscore(+patient,+score)).
modeb(*,cormack(+patient,+score)).


determination(complication/1,experience/1).
determination(complication/1,hypertension/1).
determination(complication/1,diabetes/1).
determination(complication/1,copd/1).
determination(complication/1,asthma/1).
determination(complication/1,coronary_artery_disease/1).
determination(complication/1,other_conditions/1).
determination(complication/1,ic/1).
determination(complication/1,indication/1).
determination(complication/1,diagnostic/1).
determination(complication/1,patientobese/1).
determination(complication/1,high_arched_palate/1).
determination(complication/1,shortneck/1).
determination(complication/1,necktrauma/1).
determination(complication/1,beardormoustache/1).
determination(complication/1,largetongue/1).
determination(complication/1,openingmouth/1).
determination(complication/1,thyromentaldistance/1).
determination(complication/1,betweenhyoidboneandthyroid/1).
determination(complication/1,tumor/1).
determination(complication/1,epiglottitis/1).
determination(complication/1,recentnecksurgery/1).
determination(complication/1,hematoma/1).
determination(complication/1,cervicalcollar/1).
determination(complication/1,elderly/1).
determination(complication/1,numerosonde/1).
determination(complication/1,niveaufixation/1).
determination(complication/1,laryngodifficile/1).
determination(complication/1,nombretentatives/1).
determination(complication/1,autreoperateur/1).
determination(complication/1,intubation_duration/1).
determination(complication/1,eichman/1).
determination(complication/1,moyensupraglottique/1).
determination(complication/1,intubationdifficile/1).
determination(complication/1,hypotension/1).
determination(complication/1,desaturation/1).
determination(complication/1,barotrauma/1).
determination(complication/1,dental_fracture/1).
determination(complication/1,cardiac_arrest/1).
determination(complication/1,bradycardia/1).
determination(complication/1,selective_intubation/1).
determination(complication/1,esophageal_intubation/1).
determination(complication/1,extubation/1).
determination(complication/1,lemonscore/2).
determination(complication/1,cormack/2).

:- begin_bg.
patient(patient115).
experience(patient115).
hypertension(patient115).
diabetes(patient115).
indication(patient115).
patientobese(patient115).
shortneck(patient115).
openingmouth(patient115).
hypotension(patient115).
desaturation(patient115).
lemonscore(patient115,2).
cormack(patient115,2).
patient(patient9).
experience(patient9).
hypertension(patient9).
diabetes(patient9).
coronary_artery_disease(patient9).
high_arched_palate(patient9).
largetongue(patient9).
elderly(patient9).
laryngodifficile(patient9).
hypotension(patient9).
desaturation(patient9).
cardiac_arrest(patient9).
lemonscore(patient9,3).
cormack(patient9,3).
hardlaryngo(patient9).
patient(patient86).
desaturation(patient86).
lemonscore(patient86,1).
cormack(patient86,0).
patient(patient65).
experience(patient65).
hypertension(patient65).
diabetes(patient65).
coronary_artery_disease(patient65).
patientobese(patient65).
beardormoustache(patient65).
largetongue(patient65).
elderly(patient65).
intubationdifficile(patient65).
desaturation(patient65).
lemonscore(patient65,2).
cormack(patient65,2).
patient(patient37).
experience(patient37).
coronary_artery_disease(patient37).
ic(patient37).
high_arched_palate(patient37).
largetongue(patient37).
laryngodifficile(patient37).
autreoperateur(patient37).
eichman(patient37).
intubationdifficile(patient37).
desaturation(patient37).
cardiac_arrest(patient37).
lemonscore(patient37,2).
cormack(patient37,3).
hardlaryngo(patient37).
patient(patient70).
coronary_artery_disease(patient70).
elderly(patient70).
hypotension(patient70).
desaturation(patient70).
lemonscore(patient70,1).
cormack(patient70,0).
patient(patient117).
experience(patient117).
hypertension(patient117).
diabetes(patient117).
ic(patient117).
laryngodifficile(patient117).
autreoperateur(patient117).
eichman(patient117).
intubationdifficile(patient117).
desaturation(patient117).
cardiac_arrest(patient117).
lemonscore(patient117,1).
cormack(patient117,3).
hardlaryngo(patient117).
patient(patient22).
experience(patient22).
copd(patient22).
ic(patient22).
high_arched_palate(patient22).
elderly(patient22).
hypotension(patient22).
desaturation(patient22).
cardiac_arrest(patient22).
lemonscore(patient22,2).
cormack(patient22,2).
patient(patient89).
desaturation(patient89).
lemonscore(patient89,1).
cormack(patient89,2).
patient(patient30).
hypertension(patient30).
diabetes(patient30).
hypotension(patient30).
lemonscore(patient30,1).
cormack(patient30,0).
patient(patient60).
experience(patient60).
hypertension(patient60).
copd(patient60).
shortneck(patient60).
elderly(patient60).
hypotension(patient60).
lemonscore(patient60,0).
cormack(patient60,2).
patient(patient16).
high_arched_palate(patient16).
largetongue(patient16).
numerosonde(patient16).
niveaufixation(patient16).
laryngodifficile(patient16).
autreoperateur(patient16).
eichman(patient16).
moyensupraglottique(patient16).
intubationdifficile(patient16).
hypotension(patient16).
desaturation(patient16).
cardiac_arrest(patient16).
selective_intubation(patient16).
esophageal_intubation(patient16).
lemonscore(patient16,2).
cormack(patient16,4).
hardlaryngo(patient16).
patient(patient95).
experience(patient95).
copd(patient95).
openingmouth(patient95).
hypotension(patient95).
lemonscore(patient95,2).
cormack(patient95,0).
patient(patient5).
hypertension(patient5).
diabetes(patient5).
patientobese(patient5).
largetongue(patient5).
laryngodifficile(patient5).
autreoperateur(patient5).
eichman(patient5).
intubationdifficile(patient5).
desaturation(patient5).
cardiac_arrest(patient5).
lemonscore(patient5,2).
cormack(patient5,3).
hardlaryngo(patient5).
patient(patient20).
experience(patient20).
laryngodifficile(patient20).
eichman(patient20).
intubationdifficile(patient20).
desaturation(patient20).
dental_fracture(patient20).
cardiac_arrest(patient20).
lemonscore(patient20,1).
cormack(patient20,3).
hardlaryngo(patient20).
patient(patient55).
experience(patient55).
hypertension(patient55).
diabetes(patient55).
thyromentaldistance(patient55).
elderly(patient55).
autreoperateur(patient55).
hypotension(patient55).
lemonscore(patient55,0).
cormack(patient55,0).
patient(patient10).
patientobese(patient10).
shortneck(patient10).
hypotension(patient10).
desaturation(patient10).
bradycardia(patient10).
lemonscore(patient10,2).
cormack(patient10,0).
patient(patient88).
hypertension(patient88).
diabetes(patient88).
coronary_artery_disease(patient88).
ic(patient88).
indication(patient88).
high_arched_palate(patient88).
elderly(patient88).
niveaufixation(patient88).
autreoperateur(patient88).
hypotension(patient88).
desaturation(patient88).
cardiac_arrest(patient88).
lemonscore(patient88,1).
cormack(patient88,2).
patient(patient8).
copd(patient8).
beardormoustache(patient8).
largetongue(patient8).
laryngodifficile(patient8).
autreoperateur(patient8).
eichman(patient8).
intubationdifficile(patient8).
hypotension(patient8).
desaturation(patient8).
extubation(patient8).
lemonscore(patient8,2).
cormack(patient8,4).
hardlaryngo(patient8).
patient(patient52).
experience(patient52).
largetongue(patient52).
numerosonde(patient52).
niveaufixation(patient52).
selective_intubation(patient52).
lemonscore(patient52,1).
cormack(patient52,2).
patient(patient103).
diabetes(patient103).
laryngodifficile(patient103).
autreoperateur(patient103).
intubation_duration(patient103).
desaturation(patient103).
esophageal_intubation(patient103).
lemonscore(patient103,1).
cormack(patient103,3).
hardlaryngo(patient103).
patient(patient82).
diabetes(patient82).
autreoperateur(patient82).
intubationdifficile(patient82).
hypotension(patient82).
desaturation(patient82).
esophageal_intubation(patient82).
lemonscore(patient82,1).
cormack(patient82,2).
patient(patient116).
experience(patient116).
asthma(patient116).
indication(patient116).
cardiac_arrest(patient116).
bradycardia(patient116).
lemonscore(patient116,1).
cormack(patient116,2).
patient(patient18).
experience(patient18).
hypotension(patient18).
lemonscore(patient18,1).
cormack(patient18,0).
patient(patient49).
experience(patient49).
high_arched_palate(patient49).
shortneck(patient49).
openingmouth(patient49).
thyromentaldistance(patient49).
laryngodifficile(patient49).
lemonscore(patient49,4).
cormack(patient49,3).
hardlaryngo(patient49).
patient(patient113).
lemonscore(patient113,1).
cormack(patient113,0).
patient(patient53).
beardormoustache(patient53).
largetongue(patient53).
laryngodifficile(patient53).
lemonscore(patient53,2).
cormack(patient53,3).
hardlaryngo(patient53).
patient(patient44).
experience(patient44).
lemonscore(patient44,1).
cormack(patient44,2).
patient(patient56).
hypertension(patient56).
patientobese(patient56).
shortneck(patient56).
numerosonde(patient56).
niveaufixation(patient56).
lemonscore(patient56,0).
cormack(patient56,2).
patient(patient106).
beardormoustache(patient106).
niveaufixation(patient106).
lemonscore(patient106,0).
cormack(patient106,2).
patient(patient97).
experience(patient97).
hypertension(patient97).
diabetes(patient97).
patientobese(patient97).
shortneck(patient97).
thyromentaldistance(patient97).
laryngodifficile(patient97).
lemonscore(patient97,2).
cormack(patient97,3).
hardlaryngo(patient97).
patient(patient79).
patientobese(patient79).
laryngodifficile(patient79).
autreoperateur(patient79).
lemonscore(patient79,1).
cormack(patient79,3).
hardlaryngo(patient79).
patient(patient1).
hypertension(patient1).
coronary_artery_disease(patient1).
ic(patient1).
indication(patient1).
beardormoustache(patient1).
elderly(patient1).
laryngodifficile(patient1).
lemonscore(patient1,2).
cormack(patient1,4).
hardlaryngo(patient1).
patient(patient96).
experience(patient96).
shortneck(patient96).
betweenhyoidboneandthyroid(patient96).
laryngodifficile(patient96).
eichman(patient96).
intubationdifficile(patient96).
lemonscore(patient96,2).
cormack(patient96,3).
hardlaryngo(patient96).
patient(patient85).
lemonscore(patient85,1).
cormack(patient85,2).
patient(patient34).
patientobese(patient34).
shortneck(patient34).
lemonscore(patient34,2).
cormack(patient34,0).
patient(patient47).
lemonscore(patient47,1).
cormack(patient47,2).
patient(patient100).
hypertension(patient100).
diabetes(patient100).
lemonscore(patient100,1).
cormack(patient100,0).
patient(patient12).
experience(patient12).
copd(patient12).
coronary_artery_disease(patient12).
patientobese(patient12).
high_arched_palate(patient12).
beardormoustache(patient12).
largetongue(patient12).
laryngodifficile(patient12).
lemonscore(patient12,4).
cormack(patient12,3).
hardlaryngo(patient12).

hard_intubation(Patient) :- lemonscore(Patient, Score), Score @> 4.
hardlaryngo(Patient) :- cormack(Patient, Score), Score @> 2.
hard_intubation(Patient) :- hardlaryngo(Patient).
:- end_bg.

:- begin_in_pos.
complication(patient115).
complication(patient9).
complication(patient86).
complication(patient65).
complication(patient37).
complication(patient70).
complication(patient117).
complication(patient22).
complication(patient89).
complication(patient30).
complication(patient60).
complication(patient16).
complication(patient95).
complication(patient5).
complication(patient20).
complication(patient55).
complication(patient10).
complication(patient88).
complication(patient8).
complication(patient52).
complication(patient103).
complication(patient82).
complication(patient116).
complication(patient18).
:- end_in_pos.

:- begin_in_neg.
complication(patient49).
complication(patient113).
complication(patient53).
complication(patient44).
complication(patient56).
complication(patient106).
complication(patient97).
complication(patient79).
complication(patient1).
complication(patient96).
complication(patient85).
complication(patient34).
complication(patient47).
complication(patient100).
complication(patient12).
:- end_in_neg.
