modeh(1,complication(+patient)).
modeb(*,experience(+patient)).
modeb(*,age(+patient)).
modeb(*,sex(+patient)).
modeb(*,hypertension(+patient)).
modeb(*,diabetes(+patient)).
modeb(*,copd(+patient)).
modeb(*,asthma(+patient)).
modeb(*,coronary_artery_disease(+patient)).
modeb(*,other_conditions(+patient)).
modeb(*,ic(+patient)).
modeb(*,indication(+patient)).
modeb(*,diagnostic(+patient)).
modeb(*,patientobese(+patient)).
modeb(*,high_arched_palate(+patient)).
modeb(*,shortneck(+patient)).
modeb(*,necktrauma(+patient)).
modeb(*,beardormoustache(+patient)).
modeb(*,largetongue(+patient)).
modeb(*,openingmouth(+patient)).
modeb(*,thyromentaldistance(+patient)).
modeb(*,betweenhyoidboneandthyroid(+patient)).
modeb(*,tumor(+patient)).
modeb(*,epiglottitis(+patient)).
modeb(*,recentnecksurgery(+patient)).
modeb(*,hematoma(+patient)).
modeb(*,cervicalcollar(+patient)).
modeb(*,elderly(+patient)).
modeb(*,numerosonde(+patient)).
modeb(*,niveaufixation(+patient)).
modeb(*,laryngodifficile(+patient)).
modeb(*,nombretentatives(+patient)).
modeb(*,autreoperateur(+patient)).
modeb(*,intubation_duration(+patient)).
modeb(*,eichman(+patient)).
modeb(*,moyensupraglottique(+patient)).
modeb(*,intubationdifficile(+patient)).
modeb(*,hypotension(+patient)).
modeb(*,desaturation(+patient)).
modeb(*,barotrauma(+patient)).
modeb(*,dental_fracture(+patient)).
modeb(*,cardiac_arrest(+patient)).
modeb(*,bradycardia(+patient)).
modeb(*,selective_intubation(+patient)).
modeb(*,esophageal_intubation(+patient)).
modeb(*,extubation(+patient)).
modeb(*,lemonscore(+patient,+score)).
modeb(*,cormack(+patient,+score)).


determination(complication/1,experience/1).
determination(complication/1,age/1).
determination(complication/1,sex/1).
determination(complication/1,hypertension/1).
determination(complication/1,diabetes/1).
determination(complication/1,copd/1).
determination(complication/1,asthma/1).
determination(complication/1,coronary_artery_disease/1).
determination(complication/1,other_conditions/1).
determination(complication/1,ic/1).
determination(complication/1,indication/1).
determination(complication/1,diagnostic/1).
determination(complication/1,patientobese/1).
determination(complication/1,high_arched_palate/1).
determination(complication/1,shortneck/1).
determination(complication/1,necktrauma/1).
determination(complication/1,beardormoustache/1).
determination(complication/1,largetongue/1).
determination(complication/1,openingmouth/1).
determination(complication/1,thyromentaldistance/1).
determination(complication/1,betweenhyoidboneandthyroid/1).
determination(complication/1,tumor/1).
determination(complication/1,epiglottitis/1).
determination(complication/1,recentnecksurgery/1).
determination(complication/1,hematoma/1).
determination(complication/1,cervicalcollar/1).
determination(complication/1,elderly/1).
determination(complication/1,numerosonde/1).
determination(complication/1,niveaufixation/1).
determination(complication/1,laryngodifficile/1).
determination(complication/1,nombretentatives/1).
determination(complication/1,autreoperateur/1).
determination(complication/1,intubation_duration/1).
determination(complication/1,eichman/1).
determination(complication/1,moyensupraglottique/1).
determination(complication/1,intubationdifficile/1).
determination(complication/1,hypotension/1).
determination(complication/1,desaturation/1).
determination(complication/1,barotrauma/1).
determination(complication/1,dental_fracture/1).
determination(complication/1,cardiac_arrest/1).
determination(complication/1,bradycardia/1).
determination(complication/1,selective_intubation/1).
determination(complication/1,esophageal_intubation/1).
determination(complication/1,extubation/1).
determination(complication/1,lemonscore/2).
determination(complication/1,cormack/2).

:- begin_bg.
patient(patient33).
hypertension(patient33).
diabetes(patient33).
coronary_artery_disease(patient33).
patientobese(patient33).
shortneck(patient33).
laryngodifficile(patient33).
cardiac_arrest(patient33).
lemonscore(patient33,2).
cormack(patient33,3).
hardlaryngo(patient33).
patient(patient64).
patientobese(patient64).
largetongue(patient64).
hypotension(patient64).
desaturation(patient64).
cardiac_arrest(patient64).
lemonscore(patient64,0).
cormack(patient64,2).
patient(patient31).
hypertension(patient31).
autreoperateur(patient31).
eichman(patient31).
intubationdifficile(patient31).
hypotension(patient31).
desaturation(patient31).
lemonscore(patient31,1).
cormack(patient31,2).
patient(patient72).
experience(patient72).
asthma(patient72).
desaturation(patient72).
bradycardia(patient72).
lemonscore(patient72,1).
cormack(patient72,0).
patient(patient28).
diabetes(patient28).
coronary_artery_disease(patient28).
elderly(patient28).
desaturation(patient28).
cardiac_arrest(patient28).
lemonscore(patient28,1).
cormack(patient28,2).
patient(patient92).
experience(patient92).
hypertension(patient92).
autreoperateur(patient92).
hypotension(patient92).
lemonscore(patient92,1).
cormack(patient92,2).
patient(patient99).
experience(patient99).
sex(patient99).
hypertension(patient99).
ic(patient99).
shortneck(patient99).
openingmouth(patient99).
laryngodifficile(patient99).
hypotension(patient99).
cardiac_arrest(patient99).
lemonscore(patient99,2).
cormack(patient99,3).
hardlaryngo(patient99).
patient(patient14).
experience(patient14).
hypertension(patient14).
patientobese(patient14).
beardormoustache(patient14).
elderly(patient14).
laryngodifficile(patient14).
desaturation(patient14).
cardiac_arrest(patient14).
lemonscore(patient14,3).
cormack(patient14,3).
hardlaryngo(patient14).
patient(patient42).
experience(patient42).
hypertension(patient42).
diabetes(patient42).
shortneck(patient42).
beardormoustache(patient42).
openingmouth(patient42).
elderly(patient42).
hypotension(patient42).
lemonscore(patient42,3).
cormack(patient42,2).
patient(patient112).
sex(patient112).
hypertension(patient112).
diabetes(patient112).
patientobese(patient112).
openingmouth(patient112).
elderly(patient112).
laryngodifficile(patient112).
eichman(patient112).
intubationdifficile(patient112).
desaturation(patient112).
lemonscore(patient112,0).
cormack(patient112,4).
hardlaryngo(patient112).
patient(patient94).
experience(patient94).
sex(patient94).
asthma(patient94).
thyromentaldistance(patient94).
intubation_duration(patient94).
desaturation(patient94).
lemonscore(patient94,0).
cormack(patient94,0).
patient(patient54).
sex(patient54).
hypertension(patient54).
patientobese(patient54).
shortneck(patient54).
thyromentaldistance(patient54).
betweenhyoidboneandthyroid(patient54).
niveaufixation(patient54).
cardiac_arrest(patient54).
lemonscore(patient54,3).
cormack(patient54,0).
patient(patient36).
hypertension(patient36).
ic(patient36).
patientobese(patient36).
shortneck(patient36).
largetongue(patient36).
cardiac_arrest(patient36).
lemonscore(patient36,3).
cormack(patient36,0).
patient(patient66).
experience(patient66).
hypertension(patient66).
diabetes(patient66).
high_arched_palate(patient66).
largetongue(patient66).
openingmouth(patient66).
niveaufixation(patient66).
bradycardia(patient66).
lemonscore(patient66,3).
cormack(patient66,2).
patient(patient104).
hypertension(patient104).
diabetes(patient104).
coronary_artery_disease(patient104).
patientobese(patient104).
shortneck(patient104).
thyromentaldistance(patient104).
betweenhyoidboneandthyroid(patient104).
laryngodifficile(patient104).
autreoperateur(patient104).
intubationdifficile(patient104).
desaturation(patient104).
lemonscore(patient104,3).
cormack(patient104,4).
hardlaryngo(patient104).
patient(patient3).
sex(patient3).
hypertension(patient3).
diabetes(patient3).
patientobese(patient3).
shortneck(patient3).
openingmouth(patient3).
elderly(patient3).
laryngodifficile(patient3).
eichman(patient3).
intubationdifficile(patient3).
cardiac_arrest(patient3).
lemonscore(patient3,4).
cormack(patient3,3).
hardlaryngo(patient3).
patient(patient81).
copd(patient81).
laryngodifficile(patient81).
autreoperateur(patient81).
hypotension(patient81).
desaturation(patient81).
cardiac_arrest(patient81).
lemonscore(patient81,0).
cormack(patient81,3).
hardlaryngo(patient81).
patient(patient25).
sex(patient25).
hypertension(patient25).
diabetes(patient25).
patientobese(patient25).
shortneck(patient25).
elderly(patient25).
cardiac_arrest(patient25).
lemonscore(patient25,3).
cormack(patient25,0).
patient(patient4).
experience(patient4).
high_arched_palate(patient4).
largetongue(patient4).
openingmouth(patient4).
elderly(patient4).
laryngodifficile(patient4).
autreoperateur(patient4).
hypotension(patient4).
cardiac_arrest(patient4).
lemonscore(patient4,4).
cormack(patient4,3).
hardlaryngo(patient4).
patient(patient27).
beardormoustache(patient27).
largetongue(patient27).
hypotension(patient27).
desaturation(patient27).
lemonscore(patient27,2).
cormack(patient27,2).
patient(patient23).
sex(patient23).
diabetes(patient23).
beardormoustache(patient23).
largetongue(patient23).
betweenhyoidboneandthyroid(patient23).
elderly(patient23).
extubation(patient23).
lemonscore(patient23,4).
cormack(patient23,0).
patient(patient91).
sex(patient91).
patientobese(patient91).
shortneck(patient91).
hypotension(patient91).
lemonscore(patient91,0).
cormack(patient91,2).
patient(patient17).
experience(patient17).
indication(patient17).
patientobese(patient17).
shortneck(patient17).
openingmouth(patient17).
eichman(patient17).
cardiac_arrest(patient17).
lemonscore(patient17,3).
cormack(patient17,0).
patient(patient80).
hypertension(patient80).
ic(patient80).
patientobese(patient80).
shortneck(patient80).
hypotension(patient80).
cardiac_arrest(patient80).
lemonscore(patient80,0).
cormack(patient80,2).
patient(patient109).
diabetes(patient109).
copd(patient109).
beardormoustache(patient109).
openingmouth(patient109).
elderly(patient109).
lemonscore(patient109,2).
cormack(patient109,2).
patient(patient63).
lemonscore(patient63,1).
cormack(patient63,0).
patient(patient24).
lemonscore(patient24,1).
cormack(patient24,0).
patient(patient101).
sex(patient101).
indication(patient101).
niveaufixation(patient101).
lemonscore(patient101,1).
cormack(patient101,0).
patient(patient75).
experience(patient75).
sex(patient75).
openingmouth(patient75).
lemonscore(patient75,0).
cormack(patient75,0).
patient(patient105).
sex(patient105).
lemonscore(patient105,1).
cormack(patient105,0).
patient(patient46).
sex(patient46).
lemonscore(patient46,1).
cormack(patient46,0).
patient(patient68).
lemonscore(patient68,1).
cormack(patient68,2).
patient(patient59).
experience(patient59).
laryngodifficile(patient59).
lemonscore(patient59,1).
cormack(patient59,3).
hardlaryngo(patient59).
patient(patient118).
experience(patient118).
hypertension(patient118).
diabetes(patient118).
patientobese(patient118).
thyromentaldistance(patient118).
laryngodifficile(patient118).
eichman(patient118).
intubationdifficile(patient118).
lemonscore(patient118,0).
cormack(patient118,3).
hardlaryngo(patient118).
patient(patient62).
lemonscore(patient62,1).
cormack(patient62,0).
patient(patient39).
lemonscore(patient39,1).
cormack(patient39,2).
patient(patient111).
copd(patient111).
ic(patient111).
lemonscore(patient111,1).
cormack(patient111,0).
patient(patient51).
experience(patient51).
diabetes(patient51).
indication(patient51).
elderly(patient51).
lemonscore(patient51,1).
cormack(patient51,2).
patient(patient84).
sex(patient84).
hypertension(patient84).
diabetes(patient84).
indication(patient84).
patientobese(patient84).
niveaufixation(patient84).
intubation_duration(patient84).
lemonscore(patient84,1).
cormack(patient84,2).

hard_intubation(Patient) :- lemonscore(Patient, Score), Score @> 4.
hardlaryngo(Patient) :- cormack(Patient, Score), Score @> 2.
hard_intubation(Patient) :- hardlaryngo(Patient).
:- end_bg.

:- begin_in_pos.
complication(patient33).
complication(patient64).
complication(patient31).
complication(patient72).
complication(patient28).
complication(patient92).
complication(patient99).
complication(patient14).
complication(patient42).
complication(patient112).
complication(patient94).
complication(patient54).
complication(patient36).
complication(patient66).
complication(patient104).
complication(patient3).
complication(patient81).
complication(patient25).
complication(patient4).
complication(patient27).
complication(patient23).
complication(patient91).
complication(patient17).
complication(patient80).
:- end_in_pos.

:- begin_in_neg.
complication(patient109).
complication(patient63).
complication(patient24).
complication(patient101).
complication(patient75).
complication(patient105).
complication(patient46).
complication(patient68).
complication(patient59).
complication(patient118).
complication(patient62).
complication(patient39).
complication(patient111).
complication(patient51).
complication(patient84).
:- end_in_neg.
